# Generated by Django 6.0.7 on 2026-07-28 10:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WazuhSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], max_length=10)),
                ('alerts_fetched', models.IntegerField(default=0)),
                ('alerts_ingested', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('sync_started_at', models.DateTimeField(auto_now_add=True)),
                ('sync_completed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wazuh_sync_logs', to='authentication.tenant')),
            ],
            options={
                'db_table': 'cs_wazuh_sync_logs',
                'ordering': ['-sync_started_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('source_port', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('HTTP', 'HTTP'), ('HTTPS', 'HTTPS'), ('DNS', 'DNS'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('bytes_sent', models.BigIntegerField(blank=True, null=True)),
                ('bytes_received', models.BigIntegerField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, help_text='Connection duration in milliseconds', null=True)),
                ('raw_data', models.JSONField(help_text='JSONB: full Wazuh/syslog alert payload')),
                ('log_hash', models.CharField(editable=False, help_text='SHA-256 hash of raw_data for tamper detection', max_length=64)),
                ('event_source', models.CharField(choices=[('WAZUH', 'Wazuh Agent'), ('MANUAL', 'Manual Entry'), ('API_FEED', 'External API Feed'), ('SIMULATOR', 'Test Simulator')], default='WAZUH', max_length=20)),
                ('wazuh_alert_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('agent_hostname', models.CharField(blank=True, max_length=255)),
                ('ml_classification', models.CharField(blank=True, help_text='ML model output: Normal/DoS/Probe/R2L/U2R', max_length=100)),
                ('ml_confidence', models.FloatField(blank=True, help_text='Classification confidence 0-1', null=True)),
                ('is_threat', models.BooleanField(blank=True, null=True)),
                ('event_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_events', to='authentication.tenant')),
            ],
            options={
                'db_table': 'cs_network_events',
                'ordering': ['-event_timestamp'],
                'indexes': [models.Index(fields=['tenant', 'event_timestamp'], name='cs_network__tenant__f0f943_idx'), models.Index(fields=['source_ip', 'is_threat'], name='cs_network__source__bcbc7c_idx'), models.Index(fields=['tenant', 'is_threat', 'event_timestamp'], name='cs_network__tenant__eefc0e_idx')],
            },
        ),
    ]
