# Generated by Django 6.0.7 on 2026-08-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkevent',
            name='event_source',
            field=models.CharField(choices=[('WAZUH', 'Wazuh Agent'), ('MANUAL', 'Manual Entry'), ('API_FEED', 'External API Feed'), ('SIMULATOR', 'Test Simulator'), ('SURICATA', 'Suricata NIDS')], default='WAZUH', max_length=20),
        ),
    ]
