#!/usr/bin/env python3
"""
Suricata EVE JSON Watcher — CyberShield Ingestion Bridge
=========================================================
Tails /var/log/suricata/eve.json and forwards each ALERT event to the
CyberShield ingestion API via POST /api/ingestion/suricata/.

Works on ALL platforms (Linux/macOS/Windows Docker Desktop) because it only
reads from a shared Docker volume — no raw packet access required.

On Windows/macOS dev: point the suricata_logs volume at a directory
containing eve.json generated by simulate_traffic.py or any test fixture.

Environment Variables:
    CYBERSHIELD_API_URL     Base URL of backend (e.g., http://backend:8000)
    SURICATA_API_TOKEN      Service-account JWT for authentication
                            (alias: CYBERSHIELD_API_TOKEN for backwards compat)
    DEFAULT_TENANT_ID       UUID of the tenant to assign events to
                            (alias: CYBERSHIELD_TENANT_ID for backwards compat)
    EVE_LOG_PATH            Path to eve.json (default: /var/log/suricata/eve.json)
    BATCH_SIZE              Events to batch per API call (default: 20)
    POLL_INTERVAL_S         Seconds between tail polls (default: 1.0)
    EVENT_TYPES             Comma-separated eve event_types to forward (default: alert)
"""

import json
import logging
import os
import sys
import time
from pathlib import Path

import requests

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    stream=sys.stdout,
)
logger = logging.getLogger("suricata-watcher")

# ── Configuration from environment ───────────────────────────────────────────
# Primary names match .env.example / docker-compose; backwards-compat aliases
# (CYBERSHIELD_API_TOKEN / CYBERSHIELD_TENANT_ID) are checked as fallbacks.
API_URL       = os.environ.get("CYBERSHIELD_API_URL",    "http://backend:8000")
API_TOKEN     = (
    os.environ.get("SURICATA_API_TOKEN")
    or os.environ.get("CYBERSHIELD_API_TOKEN", "")
)
TENANT_ID     = (
    os.environ.get("DEFAULT_TENANT_ID")
    or os.environ.get("CYBERSHIELD_TENANT_ID", "")
)
EVE_LOG_PATH  = os.environ.get("EVE_LOG_PATH",           "/var/log/suricata/eve.json")
BATCH_SIZE    = int(os.environ.get("BATCH_SIZE",          "20"))
POLL_INTERVAL = float(os.environ.get("POLL_INTERVAL_S",   "1.0"))
EVENT_TYPES   = set(os.environ.get("EVENT_TYPES",         "alert").split(","))

INGEST_URL = f"{API_URL.rstrip('/')}/api/ingestion/suricata/"


def wait_for_file(path: str, timeout_s: int = 120) -> None:
    """Block until eve.json appears (Suricata may take a moment to start)."""
    deadline = time.time() + timeout_s
    logger.info(f"Waiting for eve.json at {path} …")
    while time.time() < deadline:
        if Path(path).exists():
            logger.info("eve.json found — starting tail")
            return
        time.sleep(2)
    logger.warning(
        f"eve.json not found after {timeout_s}s. "
        "Continuing anyway — will retry on each poll."
    )


def make_session() -> requests.Session:
    """Build an authenticated requests Session."""
    session = requests.Session()
    if API_TOKEN:
        session.headers.update({"Authorization": f"Bearer {API_TOKEN}"})
    session.headers.update({"Content-Type": "application/json"})
    return session


def post_batch(session: requests.Session, batch: list) -> bool:
    """
    POST a batch of EVE events to the CyberShield ingestion API.
    Returns True if accepted (2xx), False otherwise.
    """
    payload = {
        "tenant_id": TENANT_ID,
        "events":    batch,
    }
    try:
        resp = session.post(INGEST_URL, json=payload, timeout=10)
        if resp.status_code in (200, 201, 202):
            logger.debug(f"Batch of {len(batch)} events accepted.")
            return True
        else:
            logger.warning(
                f"API rejected batch: {resp.status_code} — {resp.text[:200]}"
            )
            return False
    except requests.exceptions.ConnectionError:
        logger.warning("CyberShield backend unreachable — will retry next poll.")
        return False
    except Exception as exc:
        logger.error(f"Unexpected error posting batch: {exc}")
        return False


def tail_eve_json(path: str, session: requests.Session) -> None:
    """
    Persistently tail eve.json, forwarding alert events to CyberShield.
    Handles file rotation (Suricata log rotation) gracefully.
    """
    pos = 0
    inode = None

    while True:
        eve_path = Path(path)

        # Handle file rotation or missing file
        if eve_path.exists():
            current_inode = eve_path.stat().st_ino
            if inode is not None and current_inode != inode:
                logger.info("eve.json rotated — resetting position.")
                pos = 0
            inode = current_inode

            batch = []
            try:
                with open(path, "r", encoding="utf-8", errors="replace") as f:
                    f.seek(pos)
                    for line in f:
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            event = json.loads(line)
                        except json.JSONDecodeError:
                            continue

                        # Filter to configured event types (default: alert only)
                        if event.get("event_type") not in EVENT_TYPES:
                            continue

                        batch.append(event)

                        if len(batch) >= BATCH_SIZE:
                            post_batch(session, batch)
                            batch = []

                    pos = f.tell()

                if batch:
                    post_batch(session, batch)

            except OSError as exc:
                logger.warning(f"File read error: {exc}")
        else:
            logger.debug(f"eve.json not found at {path} — waiting …")

        time.sleep(POLL_INTERVAL)


def main():
    if not TENANT_ID:
        logger.error(
            "DEFAULT_TENANT_ID (or CYBERSHIELD_TENANT_ID) is not set. "
            "Set it in docker-compose.yml or .env and restart."
        )
        sys.exit(1)

    if not API_TOKEN:
        logger.warning(
            "SURICATA_API_TOKEN (or CYBERSHIELD_API_TOKEN) is not set. "
            "Requests will be sent without authentication — ensure the endpoint allows this."
        )

    logger.info(f"Suricata Watcher starting")
    logger.info(f"  Eve log:   {EVE_LOG_PATH}")
    logger.info(f"  API URL:   {INGEST_URL}")
    logger.info(f"  Tenant ID: {TENANT_ID}")
    logger.info(f"  Event types forwarded: {EVENT_TYPES}")

    wait_for_file(EVE_LOG_PATH)
    session = make_session()

    try:
        tail_eve_json(EVE_LOG_PATH, session)
    except KeyboardInterrupt:
        logger.info("Watcher stopped.")


if __name__ == "__main__":
    main()
