# Generated by Django 6.0.7 on 2026-07-28 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], db_index=True, default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('ESCALATED', 'Escalated')], db_index=True, default='NEW', max_length=20)),
                ('attack_type', models.CharField(choices=[('NORMAL', 'Normal'), ('DOS', 'Denial of Service'), ('PROBE', 'Probe / Reconnaissance'), ('R2L', 'Remote to Local'), ('U2R', 'User to Root'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('affected_asset', models.CharField(blank=True, max_length=255)),
                ('ml_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('network_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert', to='ingestion.networkevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='authentication.tenant')),
            ],
            options={
                'db_table': 'cs_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('CONTAINED', 'Contained'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], default='HIGH', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('alerts', models.ManyToManyField(blank=True, related_name='incidents', to='detection.alert')),
                ('lead_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_incidents', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='authentication.tenant')),
            ],
            options={
                'db_table': 'cs_incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLInferenceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_features', models.JSONField(help_text='Feature vector sent to the model')),
                ('prediction', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('inference_time_ms', models.FloatField(blank=True, null=True)),
                ('inferred_at', models.DateTimeField(auto_now_add=True)),
                ('network_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.networkevent')),
            ],
            options={
                'db_table': 'cs_ml_inference_logs',
                'ordering': ['-inferred_at'],
            },
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_mode', models.CharField(choices=[('AUTO', 'Automatic (on ML flag)'), ('MANUAL', 'Manual (analyst-triggered)')], default='MANUAL', max_length=10)),
                ('trigger_severity', models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], max_length=10, null=True)),
                ('commands', models.JSONField(help_text='List of shell command strings. E.g. ["iptables -A INPUT -s {ip} -j DROP"]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='authentication.tenant')),
            ],
            options={
                'db_table': 'cs_playbooks',
            },
        ),
        migrations.CreateModel(
            name='PlaybookExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DRY_RUN', 'Dry Run')], default='PENDING', max_length=10)),
                ('target_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('is_dry_run', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.alert')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='detection.playbook')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cs_playbook_executions',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='IPBlocklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-unblock after this datetime', null=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_blocklist', to='authentication.tenant')),
                ('playbook_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.playbookexecution')),
            ],
            options={
                'db_table': 'cs_ip_blocklist',
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['tenant', 'status', 'severity'], name='cs_alerts_tenant__a23970_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['tenant', 'created_at'], name='cs_alerts_tenant__de9962_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ipblocklist',
            unique_together={('tenant', 'ip_address')},
        ),
    ]
