# Generated by Django 6.0.7 on 2026-08-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='playbook_gated',
            field=models.BooleanField(default=False, help_text='True if auto-playbook was suppressed pending analyst review (confidence below threshold)'),
        ),
        migrations.AddField(
            model_name='mlinferencelog',
            name='dataset_source',
            field=models.CharField(default='NSL-KDD', help_text='Training dataset used by the model that produced this inference', max_length=20),
        ),
        migrations.AddField(
            model_name='mlinferencelog',
            name='shap_explanation',
            field=models.JSONField(blank=True, help_text='Top-N SHAP feature contributions: [{feature, value, shap_value, direction}]', null=True),
        ),
    ]
