# Generated by Django 6.0.7 on 2026-08-17 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('detection', '0002_add_shap_explanation_suricata_confidence_gate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.JSONField(help_text='Snapshot of metrics at generation time')),
                ('findings', models.JSONField(help_text='Compliance mapping items state')),
                ('auditor_notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='authentication.tenant')),
            ],
            options={
                'db_table': 'cs_compliance_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
