# Generated by Django 6.0.7 on 2026-07-28 10:05

import django.db.models.deletion
import django.utils.timezone
import forensics.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('detection', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('LOG_FILE', 'Log File'), ('PCAP', 'Network Capture (PCAP)'), ('DISK_IMAGE', 'Disk Image'), ('SCREENSHOT', 'Screenshot'), ('MEMORY_DUMP', 'Memory Dump'), ('REPORT', 'Report Document'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=forensics.models.evidence_upload_path)),
                ('file_name', models.CharField(editable=False, max_length=255)),
                ('file_size_bytes', models.BigIntegerField(editable=False)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('sha256_hash', models.CharField(editable=False, help_text='SHA-256 hash computed at upload time', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source_network_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.networkevent')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cs_evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChainOfCustody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('COLLECTED', 'Evidence Collected'), ('TRANSFERRED', 'Evidence Transferred'), ('ANALYZED', 'Evidence Analyzed'), ('COPIED', 'Copy Made'), ('HASHED', 'Hash Verified'), ('SUBMITTED', 'Submitted to Legal'), ('RETURNED', 'Returned to Owner')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='Physical or network location', max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_chain', to='forensics.evidence')),
            ],
            options={
                'db_table': 'cs_chain_of_custody',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ForensicCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACTIVE', 'Active Investigation'), ('PENDING_REVIEW', 'Pending Legal Review'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=20)),
                ('classification', models.CharField(choices=[('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted'), ('INTERNAL', 'Internal'), ('PUBLIC', 'Public')], default='CONFIDENTIAL', max_length=15)),
                ('attack_vector', models.CharField(blank=True, max_length=200)),
                ('affected_systems', models.JSONField(default=list, help_text='List of affected hostnames/IPs')),
                ('legal_hold', models.BooleanField(default=False, help_text='True if under legal hold — prevents deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('lead_investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_cases', to=settings.AUTH_USER_MODEL)),
                ('related_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forensic_cases', to='detection.incident')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forensic_cases', to='authentication.tenant')),
            ],
            options={
                'db_table': 'cs_forensic_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='forensics.forensiccase'),
        ),
        migrations.CreateModel(
            name='CaseTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('INITIAL_ACCESS', 'Initial Access'), ('LATERAL_MOVEMENT', 'Lateral Movement'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation'), ('DATA_EXFILTRATION', 'Data Exfiltration'), ('PERSISTENCE', 'Persistence Mechanism'), ('COMMAND_CONTROL', 'Command & Control'), ('IMPACT', 'Impact / Destruction'), ('DETECTION', 'Detection Event'), ('RESPONSE', 'Response Action'), ('OTHER', 'Other')], default='OTHER', max_length=25)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('target_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_system', models.CharField(blank=True, help_text='Log source (e.g. Wazuh, SIEM, Manual)', max_length=255)),
                ('event_time', models.DateTimeField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('network_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.networkevent')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forensics.evidence')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='forensics.forensiccase')),
            ],
            options={
                'db_table': 'cs_case_timeline',
                'ordering': ['event_time'],
            },
        ),
    ]
