# Generated by Django 6.0.7 on 2026-07-28 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Core User',
                'verbose_name_plural': 'Core Users',
                'db_table': 'tbl_user',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkAsset',
            fields=[
                ('asset_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=45)),
                ('os_type', models.CharField(max_length=100)),
                ('wazuh_agent_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Under Maintenance'), ('COMPROMISED', 'Potentially Compromised')], default='ONLINE', max_length=50)),
            ],
            options={
                'verbose_name': 'Network Asset',
                'verbose_name_plural': 'Network Assets',
                'db_table': 'tbl_network_asset',
                'ordering': ['asset_name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=255, unique=True)),
                ('domain_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=50)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'tbl_organization',
                'ordering': ['org_name'],
            },
        ),
        migrations.CreateModel(
            name='ForensicCase',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACTIVE', 'Active Investigation'), ('PENDING_REVIEW', 'Pending Review'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forensic_cases', to='core.coreuser')),
            ],
            options={
                'verbose_name': 'Forensic Case',
                'verbose_name_plural': 'Forensic Cases',
                'db_table': 'tbl_forensic_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Analyst', 'Security Analyst'), ('Investigator', 'Digital Forensic Investigator'), ('Admin', 'System Administrator'), ('Management', 'Organization Management')], default='Analyst', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('LOCKED', 'Account Locked')], default='ACTIVE', max_length=50)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='login', to='core.coreuser')),
            ],
            options={
                'verbose_name': 'Login Credential',
                'verbose_name_plural': 'Login Credentials',
                'db_table': 'tbl_login',
            },
        ),
        migrations.CreateModel(
            name='NetworkEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_ip', models.CharField(max_length=45)),
                ('destination_ip', models.CharField(max_length=45)),
                ('raw_telemetry', models.JSONField(help_text='Native PostgreSQL JSONB — full Wazuh/syslog event payload')),
                ('threat_classification', models.CharField(db_index=True, max_length=100)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='ML confidence score 0.00–100.00', max_digits=5)),
                ('sha256_hash', models.CharField(editable=False, help_text='SHA-256 seal of raw_telemetry; auto-computed on save', max_length=64)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.networkasset')),
            ],
            options={
                'verbose_name': 'Network Event',
                'verbose_name_plural': 'Network Events',
                'db_table': 'tbl_network_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContainmentAction',
            fields=[
                ('action_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('BLOCK_IP', 'Block IP Address'), ('QUARANTINE_HOST', 'Quarantine Host'), ('KILL_PROCESS', 'Kill Malicious Process'), ('ISOLATE_NETWORK', 'Network Isolation'), ('ALERT_ANALYST', 'Alert Analyst'), ('CUSTOM', 'Custom Action')], max_length=50)),
                ('target_ip', models.CharField(max_length=45)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('execution_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success'), ('SKIPPED', 'Skipped (dry-run)')], default='PENDING', max_length=50)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='containment_actions', to='core.networkevent')),
            ],
            options={
                'verbose_name': 'Containment Action',
                'verbose_name_plural': 'Containment Actions',
                'db_table': 'tbl_containment_action',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddField(
            model_name='networkasset',
            name='org',
            field=models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.organization'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='org',
            field=models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='networkevent',
            index=models.Index(fields=['asset', 'timestamp'], name='tbl_network_asset_i_3892d9_idx'),
        ),
        migrations.AddIndex(
            model_name='networkevent',
            index=models.Index(fields=['threat_classification', 'confidence_score'], name='tbl_network_threat__6534d0_idx'),
        ),
        migrations.AddIndex(
            model_name='networkevent',
            index=models.Index(fields=['source_ip'], name='tbl_network_source__0b1041_idx'),
        ),
        migrations.AddIndex(
            model_name='containmentaction',
            index=models.Index(fields=['event', 'execution_status'], name='tbl_contain_event_i_ee96c5_idx'),
        ),
        migrations.AddIndex(
            model_name='containmentaction',
            index=models.Index(fields=['target_ip'], name='tbl_contain_target__050535_idx'),
        ),
        migrations.AddIndex(
            model_name='networkasset',
            index=models.Index(fields=['org', 'status'], name='tbl_network_org_id_e5145b_idx'),
        ),
        migrations.AddIndex(
            model_name='networkasset',
            index=models.Index(fields=['ip_address'], name='tbl_network_ip_addr_387161_idx'),
        ),
    ]
